CREATE USER infisical WITH PASSWORD 'infisical';
CREATE USER twenty WITH PASSWORD 'twenty';

CREATE DATABASE infisical;
CREATE DATABASE twenty;
CREATE DATABASE core;
CREATE DATABASE metadata;

\c infisical;

GRANT ALL PRIVILEGES ON DATABASE infisical TO infisical;
CREATE SCHEMA IF NOT EXISTS public;
GRANT USAGE, CREATE ON SCHEMA public TO infisical;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO infisical;

\c twenty;

GRANT ALL PRIVILEGES ON DATABASE twenty TO twenty;
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS metadata;
GRANT ALL ON SCHEMA metadata TO twenty;
GRANT ALL ON SCHEMA core TO twenty;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA core TO twenty;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA metadata TO twenty;
ALTER ROLE twenty superuser;
CREATE SCHEMA IF NOT EXISTS graphql;
CREATE EXTENSION IF NOT EXISTS "pg_graphql"