// Generated by ReScript, PLEASE EDIT WITH CARE


let Dynamic = {};

let Request = {};

let $$Error = {};

let Head = {};

let Image = {};

let Link = {};

let Router = {};

let Res = {};

let GetServerSideProps = {
  Res: Res
};

let GetStaticPaths = {};

let GetStaticProps = {};

let Page = {
  GetServerSideProps: GetServerSideProps,
  GetStaticPaths: GetStaticPaths,
  GetStaticProps: GetStaticProps
};

let Script = {};

export {
  Dynamic,
  Request,
  $$Error,
  Head,
  Image,
  Link,
  Router,
  Page,
  Script,
}
/* No side effect */
