# If this will not give me a job as junior devops
# I do not have clue what will...
# https://docs.docker.com/compose/compose-file/05-services/#volumes
# ----------------------------------------
# Resource Presets
# ----------------------------------------
x-resource-preset-x0.25: &resource-preset-x025
  limits:
    cpus: '0.25'
    memory: 256M
x-resource-preset-x0.5: &resource-preset-x05
  limits:
    cpus: '0.5'
    memory: 512M
x-resource-preset-x1: &resource-preset-x1
  limits:
    cpus: '1'
    memory: 1G
x-resource-preset-x2: &resource-preset-x2
  limits:
    cpus: '2'
    memory: 2G
x-resource-preset-x16: &resource-preset-x16
  limits:
    cpus: '4'
    memory: 4G

# ----------------------------------------
# Logging Configuration
# ----------------------------------------
x-logging-config: &logging-default
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

# ----------------------------------------
# Restart Policy Configuration
# ----------------------------------------
x-restart-policy: &restart_policy
  condition: on-failure
  max_attempts: 3

# ----------------------------------------
# Stateful Persistence Volumes Configuration
# ----------------------------------------
# My problem there is that I know bind mounts would solve my
# problem, but there I would need to define tons of bind mounts
# into different places, and I would like to seek for more elegant
# way that would allow me to define the volumes in one place and
# then use them in different services.
# I'm actually sure the volume plugins are things that I need
# but before them I need one bind mount for ex.
# S3 bucket that would store all the data that I need to persist
#
# https://rclone.org/docker/
# docker plugin set rclone RCLONE_VERBOSE=2 config=/etc/rclone args="--vfs-cache-mode=writes --allow-other
# Local Persist ("local-persist")
# https://github.com/MatchbookLab/local-persist/tree/master
# https://github.com/rexray/rexray
# https://github.com/offen/docker-volume-backup
# This project used NFS volumes for persisting data
# https://github.com/tldr-devops/startpack/tree/main
# https://github.com/ethibox/awesome-stacks/tree/master
# https://github.com/juicedata/docker-volume-juicefs
# https://github.com/TrilliumIT/docker-zfs-plugin
# glusterfs plugin
# ---
# docker run -d \
#   -v /run/docker/plugins/:/run/docker/plugins/ \
#   -v /spacewarp/docker/plugins/local-persist:/var/lib/docker/plugin-data/ \
#   -v /spacewarp/docker/volumes:/data \
#      cwspear/docker-local-persist-volume-plugin
#
x-stateful-volume-default: &stateful-volume
  driver: local

# ----------------------------------------
# Healthcheck Configuration
# ----------------------------------------
x-healthcheck-default:
  # Avoid setting the interval too small, as docker uses much more CPU than one would expect.
  # Related issues:
  # https://github.com/moby/moby/issues/39102
  # https://github.com/moby/moby/issues/39388
  # https://github.com/getsentry/self-hosted/issues/1000
  &healthcheck-default
  interval: 60s
  timeout: 60s
  retries: 2
  start_period: 30s