name: reverse-proxy
services:
  traefik:
    image: "traefik:v2.11"
    container_name: "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN:-localhost}`)"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
    ports:
      - published: 80
        target: 80
        mode: ingress
      - published: 443
        target: 443
        mode: ingress
      - published: 8083
        target: 8080
        mode: ingress
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - reverse_proxy
      - public_tunnel
    restart: unless-stopped

networks:
  reverse_proxy:
    name: reverse_proxy
  public_tunnel:
    external: true