name: ingress
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.${DOMAIN:-localhost}`)
      - traefik.http.services.api.loadbalancer.server.port=8080
      - traefik.http.routers.api.entrypoints=web
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
      - published: 1704
        target: 1704
        mode: udp
      - published: 0
        target: 8080
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.yaml
      - source: traefik_dynamic_config
        target: /etc/traefik/traefik_dynamic.yaml
    secrets:
      - source: local_certificate
      - source: local_certificate_key
    networks:
      - ingress
    restart: unless-stopped

networks:
  ingress:
    name: "ingress"

configs:
  traefik_config:
    file: traefik.yaml
  traefik_dynamic_config:
    file: traefik_dynamic.yaml

secrets:
  local_certificate:
    file: ./certs/local-cert.pem
  local_certificate_key:
    file: ./certs/local-key.pem