version: "3.7"

services:
  #  traefik:
  #    container_name: ${SERVICE_NAME}-traefik
  #    image: traefik:v2.3
  #    command:
  #      - --api.insecure=true
  #      - --providers.docker
  #      - --providers.docker.exposedbydefault=false
  #      - --entrypoints.web.address=:80
  #    ports:
  #      - "80:80"
  #      - "8080:8080"
  #    volumes:
  #      - /var/run/docker.sock:/var/run/docker.sock

  jaeger:
    container_name: ${SERVICE_NAME}-jaeger
    image: jaegertracing/all-in-one:1.41
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.local`)"
      - "traefik.http.routers.jaeger.entrypoints=web"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
    restart: unless-stopped
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

  postgres:
    container_name: ${SERVICE_NAME}-postgres
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "${PWD}/.docker/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=keinsell
      - POSTGRES_PASSWORD=keinsell
      - POSTGRES_DATABASE=keinsell
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_ROOT_PASSWORD=keinsell
    mem_reservation: 256M
    mem_swappiness: 50
    cpu_count: 1
    cpu_percent: 1
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024m
        reservations:
          cpus: "0.25"
          memory: 512M

  redis:
    container_name: ${SERVICE_NAME}-redis
    image: redis:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis.rule=Host(`redis.local`)"
    ports:
      - "6379:6379"
    volumes:
      - "${PWD}/.docker/redis:/var/lib/redis"
    mem_reservation: 256M
    mem_swappiness: 50
    cpu_count: 1
    cpu_percent: 1
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024m
        reservations:
          cpus: "0.25"
          memory: 512M

networks:
  default:
    driver: bridge