version: "3.7"


#  docker run -d --name jaeger \
#  -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
#  -e COLLECTOR_OTLP_ENABLED=true \
#  -p 6831:6831/udp \
#  -p 6832:6832/udp \
#  -p 5778:5778 \
#  -p 16686:16686 \
#  -p 4317:4317 \
#  -p 4318:4318 \
#  -p 14250:14250 \
#  -p 14268:14268 \
#  -p 14269:14269 \
#  -p 9411:9411 \
#  jaegertracing/all-in-one:1.41

services:
  jaeger:
    container_name: ${SERVICE_NAME}-jaeger
    image: jaegertracing/all-in-one:1.41
    restart: unless-stopped
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    mem_reservation: 256M
    mem_swappiness: 50
    cpu_count: 1
    cpu_percent: 1
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024m
        reservations:
          cpus: "0.25"
          memory: 512M
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

  postgres:
    container_name: ${SERVICE_NAME}-postgres
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - "${PWD}/.cache/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    mem_reservation: 256M
    mem_swappiness: 50
    cpu_count: 1
    cpu_percent: 1
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024m
        reservations:
          cpus: "0.25"
          memory: 512M

  redis:
    container_name: ${SERVICE_NAME}-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "${PWD}/.cache/redis:/var/lib/redis"
    mem_reservation: 256M
    mem_swappiness: 50
    cpu_count: 1
    cpu_percent: 1
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024m
        reservations:
          cpus: "0.25"
          memory: 512M