name: portainer

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN:-localhost}`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.entrypoints=http
    #      - traefik.https.routers.portainer.rule=Host(`portainer.${DOMAIN:-localhost}`)
    #      - traefik.https.services.portainer.loadbalancer.server.port=9443
    #      - traefik.https.routers.portainer.entrypoints=https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: portainer_data
        target: /data
    networks:
      - public_network
    ports:
      - target: 9000
        published: 9000

volumes:
  portainer_data:
    driver: local
    name: portainer_data

networks:
  public_network:
    external: true