name: Run API

description: Starts and waits for an API running instance

runs:
  using: composite
  steps:
    - shell: bash
      run: cp example.env apps/server/.env
    - shell: bash
      run: cd apps/server && pnpm db:push
    - name: Start API
      shell: bash
      run: cd apps/server && nohup pnpm dev &
    - name: Wait on API
      shell: bash
      run: wait-on --timeout=180000 http://localhost:1337/health