githubConfigUrl: "https://github.com/keinsell/methylphenidate"

maxRunners: 15
minRunners: 3

# runnerGroup: "default"

runnerScaleSetName: "luminar-clinux-x64-x2"

containerMode:
  type: "kubernetes"
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "openebs-hostpath"
    resources:
      requests:
        storage: 5Gi
  kubernetesModeServiceAccount:
    annotations: {}

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_CONTAINER_HOOKS
            value: /home/runner/k8s/index.js
          - name: ACTIONS_RUNNER_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
    volumes:
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: "openebs-hostpath"
              resources:
                requests:
                  storage: 5Gi