name: tunnel
services:
  # ----------------------------------------
  # Cloudflare Tunnel
  # ----------------------------------------
  # This is the core service that connects the
  # local development environment to the Cloudflare
  # network. It is used to expose the local development
  # environment to the internet.
  # ----------------------------------------
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --autoupdate-freq 5m --config /etc/cloudflared/config.yml --management-diagnostics --bastion --no-chunked-encoding --url http://traefik run
    environment:
      TUNNEL_ORIGIN_CERT: /run/secrets/cloudflare_account_certificate
      TUNNEL_EDGE_IP_VERSION: auto
      TUNNEL_LOGLEVEL: debug
    user: root
    networks:
      - public_network
    secrets:
      - source: cloudflare_tunnel_credentials
      - source: cloudflare_account_certificate
    configs:
      - source: cloudflared_config
        target: /etc/cloudflared/config.yml


networks:
  public_network:
    external: true

secrets:
  cloudflare_account_certificate:
    file: "~/.cloudflared/cert.pem"
  cloudflare_tunnel_credentials:
    file: "~/.cloudflared/${CLOUDFLARE_TUNNEL_ID}.json"

configs:
  cloudflared_config:
    content: |
      tunnel: ${CLOUDFLARE_TUNNEL_ID}
      credentials-file: /run/secrets/cloudflare_tunnel_credentials
      
      originRequest: # Top-level configuration
        connectTimeout: 5s
      
      ingress:
        - hostname: traefik.plygrnd.land
          service: http://traefik
          originRequest:
            httpHostHeader: traefik.localhost
            noTLSVerify: true
            disableChunkedEncoding: true
        - hostname: test.plygrnd.land
          service: hello_world
        - service: http_status:404