githubConfigUrl: "https://github.com/keinsell/methylphenidate"

maxRunners: 10
minRunners: 0

# runnerGroup: "default"

runnerScaleSetName: "luminar-linux-x64-x2"

containerMode:
  type: "dind"

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: [ "/home/runner/run.sh" ]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "2"