name: 🐳Setup Docker

description: Sets up the docker

inputs:
  docker_username:
    description: 'Docker username'
    required: false
  docker_password:
    description: 'Docker password'
    required: false

runs:
  using: composite
  steps:
    - name: 📥 Restore Docker Cache
      uses: ScribeMD/docker-cache@0.3.6
      with:
        key: docker-engine-${{ runner.os }}

    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v1
      if: inputs.docker_username != '' && inputs.docker_password != ''
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}