name: Continuous Integration of "server"

on:
  pull_request:
    branches:
      - main
      - next
  push:
    branches:
      - next
      - main
    paths:
      - 'package.json'
      - 'yarn.lock'
      - 'apps/server/**'
      - 'packages/**'
      - 'libs/shared/**'
env:
  TF_WORKSPACE: keinsell-dev
  CONFIGU_ORG: ${{ secrets.CONFIGU_ORG }}
  CONFIGU_SECRET: ${{ secrets.CONFIGU_SECRET }}

jobs:
  # Pre-build is a quality-control step, dedicated for checking code formatting,
  # catching linting issues and other common dev-level mistakes.
  pre-build:
    name: 💡 Pre-build
    runs-on: methylphenidate-runner-set
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

  # Build is a step dedicated for building application.
  build:
    runs-on: methylphenidate-runner-set
    name: 🔨 Build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

  # Testing is a step dedicated for running all tests associated with given app.
  testing:
    runs-on: methylphenidate-runner-set
    name: 🔬 Testing
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0