name: Build Server Application

on:
  push:
    # Run only when server files were modified
    paths:
      - 'apps/server/src/**'

jobs:
  build:
    runs-on: arc-runner-set
    strategy:
      matrix:
        node: [ 18, 20 ]
        architecture:
            - x64

    name: Build with node@${{ matrix.node }} -- ${{ matrix.architecture }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest
          registry: https://registry.npmjs.org
          cache: "pnpm"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install