name: Build Server Application

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: arc-runner-set
    strategy:
      matrix:
        node: [ 14, 16, 18, 20 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install