name: Build Server Application

on:
  workflow_dispatch:
  push:

jobs:
  Explore-GitHub-Actions:
    runs-on: arc-runner-set
    strategy:
      matrix:
        node: [ 14, 16, 18, 20 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - run: npm ci
      - run: npm test

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install