name: Deploy Development APIs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - next
      - main
    paths:
      - 'package.json'
      - 'yarn.lock'
      - 'apps/server/**'
      - 'packages/**'
      - 'libs/shared/**'
env:
  TF_WORKSPACE: keinsell-dev

jobs:
  # TODO: Add testing
  deploy_dev_api:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: arc-runner-set
    timeout-minutes: 80
    #    environment: Development
    permissions:
      contents: read
      packages: write
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: ⚙️ Setup Repository
        uses: ./.github/actions/setup-project

  # Label of the container job
  container-job:
    runs-on: arc-runner-set

    services:
      # Label used to access the service container
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: --health-cmd redis-cli ping --health-interval 10s --health-timeout 5s --health-retries 5
        # Expose ports to the host operating system
        ports:
          - 6379:6379

      postgres:
        image: postgres
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        # Set environment variables for the service container
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        # Expose ports to the host operating system
        ports:
          - 5432:5432

      nats:
        image: nats
        # Set health checks to wait until nats has started
        options: --health-cmd nats --health-interval 10s --health-timeout 5s --health-retries 5
        # Expose ports to the host operating system
        ports:
          - 4222:4222

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: ⚙️ Setup Repository
        uses: ./.github/actions/setup-project