name: Deploy Development APIs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches:
      - next
      - main
    paths:
      - 'package.json'
      - 'yarn.lock'
      - 'apps/server/**'
      - 'packages/**'
      - 'libs/shared/**'
env:
  TF_WORKSPACE: keinsell-dev
  CONFIGU_ORG: ${{ secrets.CONFIGU_ORG }}
  CONFIGU_SECRET: ${{ secrets.CONFIGU_SECRET }}

jobs:
  test_api:
    name: 🧪 Test server application
    uses: ./.github/workflows/reusable-api-e2e.yml
    secrets: inherit

  deploy_dev_api:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    needs:
      - test_api
    runs-on: methylphenidate-runner-set
    timeout-minutes: 80
    #    environment: Development
    permissions:
      contents: read
      packages: write
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ⚙️ Setup Runner
        uses: ./.github/actions/setup-machine
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: ⚙️ Setup Repository
        uses: ./.github/actions/setup-project

      - name: 🐳 Publish Docker Image
        uses: docker/build-push-action@v5
        with:
          context: apps/server
          file: apps/server/build/Dockerfile
          push: true
          tags: |
            keinsell/methylphenidate-server:${{ github.sha }}
            ${{ github.event_name != 'pull_request' && 'keinsell/methylphenidate-server:dev' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # TODO: Deploy Terraform
      # TODO: Deploy Pulumi
      # TODO: Create Sentry Version