name: Deploy Development APIs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - next
      - main
    paths:
      - 'package.json'
      - 'yarn.lock'
      - 'apps/server/**'
      - 'packages/**'
      - 'libs/shared/**'
env:
  TF_WORKSPACE: keinsell-dev

jobs:
  # TODO: Add testing
  deploy_dev_api:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: arc-runner-set
    timeout-minutes: 80
    #    environment: Development
    permissions:
      contents: read
      packages: write
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: ⚙️ Setup Repository
        uses: ./.github/actions/setup-project

  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:16-bullseye

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: ⚙️ Setup Repository
        uses: ./.github/actions/setup-project